### ISSUE TITLE
Amount stuck on 0

### ISSUE THREAD

**Issue by Fennsy** [mlbonniec/MMM-Coinbase#3]
Hello,
I noticed that the amount of the bitcoin is stock on 0 (init of the variable bal in the node_helper) whereas I entered my API keys

Is this normal?
(Sorry for my English I'm French)

**Comment by mlbonniec** [comment]
Hello, the variable is indeed set to 0 when API keys are not set. Your problem is that even with API keys, the Bitcoin value remains at 0?
Did you enter the right API keys? And did you authorize the API to access the reading of your Bitcoin wallet?
(I am French too so no problem)

**Comment by Fennsy** [comment]
Yes, I've entered the apiKey and apiSecret in config.js (with the right permissions in Coinbase) but I think it do not check my apiKey, I will continue to look for where the problem may come from because it stuck on 0.

Thank's for your answer and great job for your module !

**Comment by mlbonniec** [comment]
It is indeed strange, I will also look on my side. Let me know if you find anything!
Thank you very much for your support!

**Comment by Fennsy** [comment]
I will try an update of raspbian and magicmirror because I am in 2.6.0 and I come back to you

**Comment by Fennsy** [comment]
After the update, it's the same but the error log display :

ReferenceError: account is not defined
    at /home/pi/MagicMirror/modules/MMM-Coinbase/node_helper.js:15:21
    at handleError (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/coinbase/lib/errorHandler.js:62:5)
    at onGet (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/coinbase/lib/ClientBase.js:254:10)
    at handleHttpError (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/coinbase/lib/errorHandler.js:52:5)
    at Request.onGet [as _callback] (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/coinbase/lib/ClientBase.js:160:10)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/request/request.js:1085:12)

But I have entered my apiKeys in config.js correctly :/
Hope that help you

**Comment by Fennsy** [comment]
I've find the problem ! missing "s" in account"s" in line 15 of the node_helper.js, before "[0]", I've do the modification and it work for me !

**Comment by mlbonniec** [comment]
Hi!
Sorry about that mistake... it was finally all silly! So I updated the module! Thank you for finding him! And don't hesitate to ask me again if you need anything!
